### ISSUE TITLE
Make J4 Compaitble?

### ISSUE THREAD

**Issue by tonypartridge** [mperaya/plg_fields_plupload#1]

**Comment by mperaya** [comment]
Is a work in progress. Now I'm updating a custom own framework for joomla 4 compability and the plupload plugin was part of this framework.
Hope I could have a working version in few weeks.

**Comment by mperaya** [comment]
Just I have update the plugin for J4 usage. The 1.0.x series will remain for usage with joomla 3.9.x only as the new version is no more compatible with older joomla versions. Hope this will help.
